---
# tasks file for nutanix_role_prism_pulse
- name: Setup connection to Nutanix API
  ansible.builtin.include_role:
    name: grdavies.role_nutanix_prism_api
  vars:
    role_nutanix_prism_api_host: "{{ role_nutanix_prism_pulse_host }}"
    role_nutanix_prism_api_host_username: "{{ role_nutanix_prism_pulse_host_username }}"
    role_nutanix_prism_api_host_password: "{{ role_nutanix_prism_pulse_host_password }}"
    role_nutanix_prism_api_host_port: "{{ role_nutanix_prism_pulse_host_port }}"
    role_nutanix_prism_api_host_validate_certs: "{{ role_nutanix_prism_pulse_host_validate_certs }}"
    role_nutanix_prism_api_debug: "{{ role_nutanix_prism_pulse_debug }}"

- name: Configure Pulse on "{{ role_nutanix_prism_pulse_host }}"
  uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/PrismGateway/services/rest/v1/pulse"
    method: PUT
    validate_certs: "{{ role_nutanix_prism_pulse_host_validate_certs }}"
    body_format: json
    body:
      defaultNutanixEmail: "{{ role_nutanix_prism_pulse_default_nutanix_email }}"
      emailContactList: "{{ role_nutanix_prism_pulse_email_contact_list }}"
      enable: "{{ role_nutanix_prism_pulse_status }}"
      enableDefaultNutanixEmail: "{{ role_nutanix_prism_pulse_enable_email }}"
      identificationInfoScrubbingLevel: "{{ role_nutanix_prism_pulse_scrubbing_level }}"
      isPulsePromptNeeded: "{{ role_nutanix_prism_pulse_prompt_needed }}"
      nosVersion: "{{ role_nutanix_prism_pulse_nos_version }}"
      remindLater: "{{ role_nutanix_prism_pulse_remind_later }}"
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
    status_code: 200
    return_content: true
  register: role_nutanix_prism_pulse_configure
  ignore_errors: false

- name: Debug Var role_nutanix_prism_pulse_configure
  ansible.builtin.debug:
    var: role_nutanix_prism_pulse_configure
  when: role_nutanix_prism_pulse_debug

- name: Failed to configure Pulse
  ansible.builtin.fail:
    msg: "Pulse configuration failed."
  when:
    - role_nutanix_prism_pulse_configure.failed
